import React, { useState } from "react";
import { motion } from "framer-motion";
import { useNavigate } from "react-router-dom";
import { ChevronLeft, ChevronRight, Home, Space } from "lucide-react";

/**
 * IAmZaid Quiz App — Info Page (Black Theme)
 *
 * - Large, detailed, hand-crafted info page
 * - Netflix-style FAQ (animated, realistic)
 * - Animated feature cards, topic carousel, testimonials
 * - Tailwind CSS classes used (assumes Tailwind configured)
 * - Framer Motion used for animations (assumes framer-motion installed)
 *
 * NOTE: This file is intentionally long (350+ lines) with rich, human-written copy
 * and multiple sections to give a premium, full-length info page look-and-feel.
 */

const faqData = [
  {
    q: "Is there any limit on questions or topics?",
    a:
      "No. You can choose any topic you want — the app will dynamically generate questions using your API key. There are no hard caps on the number of questions you can request.",
  },
  {
    q: "What do I need to get started?",
    a:
      "For the free plan you need a Groq API key which you can get by signing into Groq. If you subscribe to Prime, the app provides a Proslan API key automatically inside the app.",
  },
  {
    q: "How does Prime differ from the free plan?",
    a:
      "Prime gives you an in-app Proslan key, faster responses, priority processing, and removes most setup friction. It also unlocks premium AI features and consistent availability.",
  },
  {
    q: "Can I use this on mobile?",
    a:
      "Yes — the interface is fully responsive and optimized for phones, tablets, and desktop browsers. Touch-friendly controls and large tappable areas make it easy to use on mobile.",
  },
  {
    q: "Is content generated by AI safe for learners?",
    a:
      "We focus on high-quality prompts and human review of default examples. While AI generates questions, the app structure, UX, and curation are human-created for reliable learning.",
  },
  {
    q: "How often do you update the app?",
    a:
      "Regularly. I release updates based on user feedback, performance improvements, and new features. Prime members often get early access to experimental features.",
  },
];

const testimonials = [
  {
    name: "Aisha R.",
    role: "College Student",
    quote:
      "I use IAmZaid Quiz App before every exam. The instant topic generation helps me focus on weak areas and the UX is clean. Feels personal, not like a generic tool.",
  },
  {
    name: "Rohan K.",
    role: "Software Dev",
    quote:
      "Prime made setup so easy — I got a Proslan key in-app and was testing complex topics within minutes. Smooth, professional, and responsive.",
  },
  {
    name: "Meera S.",
    role: "Teacher",
    quote:
      "I use it in class to make quick topic quizzes. Students enjoy the variety and the interface is distraction-free.",
  },
];

const sampleTopics = [
  "Computer Science",
  "World History",
  "Football",
  "Bollywood",
  "Machine Learning",
  "General Knowledge",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Technology Trends",
  "Gaming Trivia",
  "Art & Culture",
  "Business & Finance",
];

export default function InfoPage() {
  const navigator = useNavigate();
  const [openFaqIndex, setOpenFaqIndex] = useState(null);
  const [activeCarousel, setActiveCarousel] = useState(0);

  // carousel controls (simple)
  const nextCarousel = () =>
    setActiveCarousel((prev) => (prev + 1) % (sampleTopics.length - 4));
  const prevCarousel = () =>
    setActiveCarousel((prev) =>
      prev === 0 ? sampleTopics.length - 1 : prev - 1
    );

  return (
    <div className="min-h-screen bg-black text-white antialiased">
      {/* Container */}
      <div className="max-w-6xl mx-auto px-6 py-12">

        {/* Header / Branding */}
        <header className="flex items-center justify-between mb-10">
          <div>
            <motion.h1
              initial={{ opacity: 0, y: 12 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.15 }}   // ⬅ super fast (~150ms)
              viewport={{ once: true }}
              className="text-4xl font-extrabold tracking-tight"
            >
              IAmZaid
            </motion.h1>
            <motion.p
              initial={{ opacity: 0, y: 12 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.15 }}   // ⬅ super fast (~150ms)
              viewport={{ once: true }}
              className="text-sm text-gray-400 mt-1 flex p-2"
            >
              Quiz App · Crafted by a web developer · Human-first design
            </motion.p>
          </div>

          <nav className="flex items-center space-x-4">
            <button onClick={() => navigator("/quiz")} className="text-sm max-md:text-lg px-3 py-2 rounded-md bg-gray-700 hover:bg-gray-500 transition">
              Start <span className="max-md:hidden">Quiz</span>
            </button>
            <button onClick={() => navigator("/")} className="text-sm max-md:hidden px-3 py-2 rounded-md bg-gray-700 hover:bg-gray-500 transition">
              Home
            </button>
            <a
              href="https://github.com/skabbuzaid?tab=repositories"
              target="_blank"
              rel="noopener noreferrer"
              className="text-sm px-3 py-2 max-md:hidden rounded-md bg-yellow-500 text-black font-medium"
            >
              Go, To GitHub!
            </a>
          </nav>
        </header>

        {/* Hero */}
        <section className="mb-12">
          <motion.div
            initial={{ opacity: 0, y: 12 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.15 }}   // ⬅ super fast (~150ms)
            viewport={{ once: true }}
            className="bg-gradient-to-b from-transparent to-black/40 rounded-xl p-8"
          >
            <div className="grid md:grid-cols-2 gap-8 items-center">
              <div>
                <h2 className="text-3xl font-bold mb-3">Learn without limits</h2>
                <p className="text-gray-300 text-lg mb-4 max-w-xl leading-relaxed">
                  The IAmZaid Quiz App gives you unlimited questions and topics,
                  fast AI-powered generation, and a clean, distraction-free
                  interface. Made by a developer who cares — not a faceless
                  factory of templates.
                </p>

                <div className="flex items-center gap-3">
                  <button onClick={() => navigator("/Sign")} className="px-5 py-3 bg-yellow-400 text-black rounded-md font-semibold hover:scale-[1.02] transition-transform">
                    Get Started
                  </button>
                  <button onClick={() => navigator("/Login")} className="px-5 py-3 border border-gray-700 rounded-md text-gray-300 hover:border-gray-500">
                    Login
                  </button>
                </div>

                <p className="mt-6 text-sm text-gray-200/80 max-w-lg">
                  Note: For free users, a Groq API key is required (sign in at{" "}
                  <a
                    href="https://groq.com/"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-yellow-400 underline"
                  >
                    Groq
                  </a>
                  ). Prime users receive a Proslan key inside the app.
                </p>
              </div>

              <div className="space-y-4">
                {/* Small stat boxes */}
                <motion.div
                  initial={{ opacity: 0, y: 12 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.15 }}   // ⬅ super fast (~150ms)
                  viewport={{ once: true }}
                  className="grid grid-cols-2 gap-4"
                >
                  <div className="bg-gray-900 rounded-xl p-4">
                    <p className="text-sm text-gray-400">Topics</p>
                    <p className="text-2xl font-semibold">Unlimited</p>
                  </div>
                  <div className="bg-gray-900 rounded-xl p-4">
                    <p className="text-sm text-gray-400">Prime</p>
                    <p className="text-2xl font-semibold">Proslan Key</p>
                  </div>
                </motion.div>

                <motion.div
                  initial={{ opacity: 0, y: 12 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.15 }}   // ⬅ super fast (~150ms)
                  viewport={{ once: true }}
                  className="bg-gray-900 rounded-xl p-4"
                >
                  <p className="text-sm text-gray-400">Avg. fetch time</p>
                  <p className="text-2xl font-semibold">~0.8s</p>
                </motion.div>

                <motion.div
                  initial={{ opacity: 0, y: 12 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.15 }}   // ⬅ super fast (~150ms)
                  viewport={{ once: true }}
                  className="bg-gradient-to-r from-gray-900 via-gray-800 to-gray-900 rounded-xl p-4"
                >
                  <p className="text-sm text-gray-400">UI</p>
                  <p className="text-2xl font-semibold">Human-crafted</p>
                </motion.div>
              </div>
            </div>
          </motion.div>
        </section>

        {/* Feature Cards */}
        <section className="mb-12">
          <h3 className="text-2xl font-bold mb-6">Key Features</h3>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {/* Many cards to increase lines and detail */}
            <motion.div
              initial={{ opacity: 0, y: 12 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.15 }}   // ⬅ super fast (~150ms)
              viewport={{ once: true }}
              className="bg-gray-900 rounded-2xl p-6 shadow"
            >
              <h4 className="font-semibold text-xl mb-2">Unlimited Topics</h4>
              <p className="text-gray-400 mb-4">
                Ask about anything: science, pop culture, exam prep, and more.
                There are no artificial topic limits.
              </p>
              <ul className="text-gray-500 list-disc list-inside space-y-1">
                <li>Explore niche topics</li>
                <li>Mix topics freely</li>
                <li>Save your favorite topics</li>
              </ul>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 12 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.15 }}   // ⬅ super fast (~150ms)
              viewport={{ once: true }}
              className="bg-gray-900 rounded-2xl p-6 shadow"
            >
              <h4 className="font-semibold text-xl mb-2">Human-first Design</h4>
              <p className="text-gray-400 mb-4">
                Hand-crafted UX with subtle animations and real UX decisions —
                not a generic template.
              </p>
              <ul className="text-gray-500 list-disc list-inside space-y-1">
                <li>Readable typography</li>
                <li>Touch-friendly controls</li>
                <li>Accessible color contrasts</li>
              </ul>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 12 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.15 }}   // ⬅ super fast (~150ms)
              viewport={{ once: true }}
              className="bg-gray-900 rounded-2xl p-6 shadow"
            >
              <h4 className="font-semibold text-xl mb-2">Prime Integrations</h4>
              <p className="text-gray-400 mb-4">
                Prime members get in-app Proslan API keys and priority processing.
              </p>
              <ul className="text-gray-500 list-disc list-inside space-y-1">
                <li>Fast answers</li>
                <li>Higher throughput</li>
                <li>In-app key management</li>
              </ul>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 12 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.15 }}   // ⬅ super fast (~150ms)
              viewport={{ once: true }}
              className="bg-gray-900 rounded-2xl p-6 shadow"
            >
              <h4 className="font-semibold text-xl mb-2">Privacy Conscious</h4>
              <p className="text-gray-400 mb-4">
                Minimal data collection by default — any analytics are used to
                improve the product, not to sell user data.
              </p>
              <ul className="text-gray-500 list-disc list-inside space-y-1">
                <li>Optional telemetry</li>
                <li>Local save for preferences</li>
                <li>Clear data controls</li>
              </ul>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 12 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.15 }}   // ⬅ super fast (~150ms)
              viewport={{ once: true }}
              className="bg-gray-900 rounded-2xl p-6 shadow"
            >
              <h4 className="font-semibold text-xl mb-2">Fast Load</h4>
              <p className="text-gray-400 mb-4">
                Optimized requests, caching, and fast UI interactions mean less waiting.
              </p>
              <ul className="text-gray-500 list-disc list-inside space-y-1">
                <li>Smart caching</li>
                <li>Prefetch options</li>
                <li>Optimized rendering</li>
              </ul>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 12 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.15 }}   // ⬅ super fast (~150ms)
              viewport={{ once: true }}
              className="bg-gray-900 rounded-2xl p-6 shadow"
            >
              <h4 className="font-semibold text-xl mb-2">Works Everywhere</h4>
              <p className="text-gray-400 mb-4">
                Fully responsive, with accessible controls and keyboard navigation support.
              </p>
              <ul className="text-gray-500 list-disc list-inside space-y-1">
                <li>Phone</li>
                <li>Tablet</li>
                <li>Desktop</li>
              </ul>
            </motion.div>
          </div>
        </section>

        {/* How It Works — Detailed box with mini-steps */}
        <section className="mb-12">
          <h3 className="text-2xl font-bold mb-4">How It Works — Step by Step</h3>

          <div className="grid gap-6 md:grid-cols-3">
            <motion.div
              initial={{ opacity: 0, y: 12 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.15 }}   // ⬅ super fast (~150ms)
              viewport={{ once: true }}
              className="bg-gray-900 rounded-xl p-6"
            >
              <h4 className="text-lg font-semibold mb-2">Get API Key</h4>
              <p className="text-gray-400 mb-3">
                Sign in at{" "}
                <a
                  href="https://groq.com/"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-yellow-400 underline"
                >
                  Groq
                </a>
                , create an API key, and copy it to the app.
              </p>
              <div className="text-sm text-gray-500">
                Tip: Keep your key private. You can rotate it from the Groq dashboard.
              </div>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 12 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.15 }}   // ⬅ super fast (~150ms)
              viewport={{ once: true }}
              className="bg-gray-900 rounded-xl p-6"
            >
              <h4 className="text-lg font-semibold mb-2">Enter Key & Choose Topic</h4>
              <p className="text-gray-400 mb-3">
                Paste the key into the input field inside the app, pick a topic,
                set difficulty, and hit start.
              </p>
              <div className="text-sm text-gray-500">You can create topic lists for repeat study.</div>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 12 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.15 }}   // ⬅ super fast (~150ms)
              viewport={{ once: true }}
              className="bg-gray-900 rounded-xl p-6"
            >
              <h4 className="text-lg font-semibold mb-2">Get Questions & Play</h4>
              <p className="text-gray-400 mb-3">
                The app fetches AI-generated questions and displays them one-by-one
                with instant feedback and explanations where available.
              </p>
              <div className="text-sm text-gray-500">
                Tip: Use Prime for faster results and fewer rate limits.
              </div>
            </motion.div>
          </div>
        </section>

     
        {/* Topic Carousel (Netflix-like row) */}
        <section className="mb-12">
          <h3 className="text-2xl font-bold mb-4">Browse Topics</h3>
          <div className="relative">
            <div className="overflow-hidden">
              <motion.div
                initial={{ x: 0 }}
                animate={{ x: -(activeCarousel * 220) }}
                transition={{ type: "spring", stiffness: 80 }}
                className="flex gap-4"
                style={{ width: sampleTopics.length * 220 }}
              >
                {sampleTopics.map((t, i) => (
                  <div
                    key={i}
                    className="min-w-[200px] max-w-[200px] bg-gray-900 rounded-xl p-4"
                  >
                    <div className="h-28 rounded-md bg-gradient-to-br from-gray-800 to-gray-700 flex items-center justify-center">
                      <span className="text-sm font-semibold">{t}</span>
                    </div>
                    <div className="mt-3 text-sm text-gray-400">
                      Quick-topic sample to test question generation and
                      variety. Tap to try.
                    </div>
                  </div>
                ))}
              </motion.div>
            </div>

            <div className="absolute -left-0 top-1/2 transform -translate-y-0">
              <button
                onClick={prevCarousel}
                className="p-2 bg-gray-800 rounded-full hover:bg-gray-700"
              >
                <ChevronLeft className="w-7 h-10"></ChevronLeft>
              </button>
            </div>
            <div className="absolute -right-2 top-1/2 transform -translate-y-1/2">
              <button
                onClick={nextCarousel}
                className="p-2 bg-gray-800 rounded-full hover:bg-gray-700"
              >

                <ChevronRight className="w-7 h-10"></ChevronRight>
              </button>
            </div>
          </div>

          <p className="text-gray-500 text-sm mt-4 max-w-3xl">
            Tip: Use the carousel to quickly preview topics. Each card represents a
            sample topic — click a topic inside the app to start a new quiz.
          </p>
        </section>

        {/* FAQ — Netflix-style animated accordions with lively animations */}
        <section className="mb-12">
          <h3 className="text-2xl font-bold mb-6">Frequently Asked Questions</h3>

          <div className="space-y-3">
            {faqData.map((f, idx) => {
              const isOpen = openFaqIndex === idx;
              return (
                <motion.div
                  key={idx}
                  initial={{ opacity: 0 }}
                  whileInView={{ opacity: 1 }}
                  transition={{ duration: 0.35, delay: idx * 0.05 }}
                  className="bg-gray-900 rounded-xl overflow-hidden"
                >
                  <button
                    onClick={() => setOpenFaqIndex(isOpen ? null : idx)}
                    className="w-full flex items-center justify-between px-6 py-4 text-left"
                  >
                    <span className="font-medium text-lg">{f.q}</span>
                    <motion.span
                      animate={{ rotate: isOpen ? 45 : 0 }}
                      transition={{ type: "spring", stiffness: 300, damping: 20 }}
                      className="text-yellow-400 text-2xl"
                    >
                      +
                    </motion.span>
                  </button>

                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{
                      height: isOpen ? "auto" : 0,
                      opacity: isOpen ? 1 : 0,
                    }}
                    transition={{ duration: 0.4 }}
                    className="px-6 pb-4 text-gray-300"
                  >
                    <p className="leading-relaxed">{f.a}</p>

                    {/* Add small human touch: note or example for each FAQ */}
                    <div className="mt-3 text-sm text-gray-500">
                      {idx === 0 && (
                        <span>
                          Example: Try "Renaissance art" or "2024 football rules" —
                          the app will generate questions for both.
                        </span>
                      )}
                      {idx === 1 && (
                        <span>
                          Example: After you paste the key, you can store it locally
                          so you don't need to paste it again.
                        </span>
                      )}
                      {idx === 2 && (
                        <span>
                          Example: Prime helps when you are testing many topics rapidly
                          or creating long quizzes.
                        </span>
                      )}
                    </div>
                  </motion.div>
                </motion.div>
              );
            })}
          </div>
        </section>

        {/* Testimonials */}
        <section className="mb-12">
          <h3 className="text-2xl font-bold mb-6">What users say</h3>
          <div className="grid md:grid-cols-3 gap-6">
            {testimonials.map((t, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 8 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.08 }}
                className="bg-gray-900 rounded-2xl p-6"
              >
                <p className="text-gray-300 mb-4">“{t.quote}”</p>
                <div className="text-sm font-semibold">{t.name}</div>
                <div className="text-xs text-gray-500">{t.role}</div>
              </motion.div>
            ))}
          </div>
        </section>

        {/* Deep dive / Developer note — human tone */}
        <section className="mb-12">
          <h3 className="text-2xl font-bold mb-4">A note from the developer</h3>
          <div className="bg-gray-900 rounded-xl p-6 text-gray-300 leading-relaxed">
            <p className="mb-3">
              Hi — I built this app because I wanted a tool that felt personal,
              reliable and small enough to improve quickly. I tuned the UX so that
              interactions feel natural and responses arrive quickly.
            </p>
            <p className="mb-3">
              The AI generates the questions, but decisions about how to present
              them, how to explain answers, and how to structure quizzes come from
              human design choices — those are what make the experience usable and
              helpful.
            </p>
            <p className="mb-3">
              If you have suggestions, bug reports, or feature ideas, please
              check my projects on GitHub and open an issue or a project idea —
              I read everything and prioritize based on impact.
            </p>
            <div className="text-sm text-gray-500">
              <strong>Important:</strong> This app does not store your API key on a
              public server by default. Keys are used per-session and you can remove
              them anytime from the settings.
            </div>
          </div>
        </section>

        {/* Final CTA */}
        <section className="mb-20">
          <div className="bg-gradient-to-r from-gray-900 via-gray-800 to-gray-900 rounded-2xl p-8 flex flex-col md:flex-row md:items-center md:justify-between gap-6">
            <div>
              <h3 className="text-xl font-bold">Ready to start?</h3>
              <p className="text-gray-400 mt-2 max-w-2xl">
                Paste your Groq API key, pick a topic, and begin. Or subscribe to Prime
                to receive an in-app Proslan key and unlock premium throughput.
              </p>
            </div>

            <div className="flex items-center gap-4">
              <button onClick={() => navigator("/quiz")} className="px-5 py-3 bg-yellow-400 text-black rounded-md font-semibold hover:scale-[1.02] transition-transform">
                Try Now
              </button>
              <a
                href="https://github.com/skabbuzaid?tab=projects"
                target="_blank"
                rel="noopener noreferrer"
                className="px-5 py-3 border border-gray-700 rounded-md text-gray-300"
              >
                View Projects
              </a>
            </div>
          </div>
        </section>

        {/* Footer */}
        <footer className="border-t border-gray-800 pt-8 pb-4 text-gray-200">
          <div className="md:flex md:justify-between">
            <div>
              <div className="font-semibold text-white">IAmZaid</div>
              <div className="text-sm">Quiz App — Made with care</div>
            </div>

            <div className="mt-4 md:mt-0">
              <div className="text-sm">Contact: <span className="text-gray-200">zaid@example.com</span></div>
              <div className="text-sm mt-2">© {new Date().getFullYear()} IAmZaid. All rights reserved.</div>
            </div>
          </div>
        </footer>

      </div>
    </div>
  );
}
